# Default values for greenbone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageRegistry: registry.community.greenbone.net/community
  storageClass: longhorn
  feedRelease: "24.10"

# Vulnerability Tests
vulnerabilityTests:
  enabled: true
  image:
    repository: vulnerability-tests
    tag: ""
  env:
    FEED_RELEASE: "24.10"
    KEEP_ALIVE: 1
  volumes:
    - name: vtData
      mountPath: /mnt

# Notus Data
notusData:
  enabled: true
  image:
    repository: notus-data
    tag: ""
  env:
    KEEP_ALIVE: 1
  volumes:
    - name: notusData
      mountPath: /mnt

# SCAP Data
scapData:
  enabled: true
  image:
    repository: scap-data
    tag: ""
  env:
    KEEP_ALIVE: 1
  volumes:
    - name: scapData
      mountPath: /mnt

# CERT Bund Data
certBundData:
  enabled: true
  image:
    repository: cert-bund-data
    tag: ""
  env:
    KEEP_ALIVE: 1
  volumes:
    - name: certData
      mountPath: /mnt

# DFN CERT Data
dfnCertData:
  enabled: true
  image:
    repository: dfn-cert-data
    tag: ""
  env:
    KEEP_ALIVE: 1
  volumes:
    - name: certData
      mountPath: /mnt

# Data Objects
dataObjects:
  enabled: true
  image:
    repository: data-objects
    tag: ""
  env:
    FEED_RELEASE: "24.10"
    KEEP_ALIVE: 1
  volumes:
    - name: dataObjects
      mountPath: /mnt

# Report Formats
reportFormats:
  enabled: true
  image:
    repository: report-formats
    tag: ""
  env:
    FEED_RELEASE: "24.10"
    KEEP_ALIVE: 1
  volumes:
    - name: dataObjects
      mountPath: /mnt

# GPG Data
gpgData:
  enabled: true
  image:
    repository: gpg-data
    tag: ""
  volumes:
    - name: gpgData
      mountPath: /mnt

# Redis Server
redisServer:
  enabled: true
  image:
    repository: redis-server
    tag: ""
  volumes:
    - name: redis-socket
      mountPath: /run/redis/

# PG GVM
pgGvm:
  enabled: true
  image:
    repository: pg-gvm
    tag: stable
  volumes:
    - name: psql-data
      mountPath: /var/lib/postgresql
    - name: psql-socket
      mountPath: /var/run/postgresql

# PG GVM Migrator
pgGvmMigrator:
  enabled: true
  image:
    repository: pg-gvm-migrator
    tag: stable
  volumes:
    - name: psql-data
      mountPath: /var/lib/postgresql
    - name: psql-socket
      mountPath: /var/run/postgresql

# GVMD
gvmd:
  enabled: true
  image:
    repository: gvmd
    tag: stable
  volumes:
    - name: gvmdData
      mountPath: /var/lib/gvm
    - name: scapData
      mountPath: /var/lib/gvm/scap-data/
    - name: certData
      mountPath: /var/lib/gvm/cert-data
    - name: dataObjects
      mountPath: /var/lib/gvm/data-objects/gvmd
    - name: vtData
      mountPath: /var/lib/openvas/plugins
    - name: psqlData
      mountPath: /var/lib/postgresql
    - name: gvmdSocket
      mountPath: /run/gvmd
    - name: ospdOpenvasSocket
      mountPath: /run/ospd
    - name: psqlSocket
      mountPath: /var/run/postgresql

# GSA
gsa:
  enabled: true
  image:
    repository: gsa
    tag: stable-slim
  env:
    MOUNT_PATH: "/mnt/web"
    KEEP_ALIVE: 1
  volumes:
    - name: gsaData
      mountPath: /mnt/web

# GSAD
gsad:
  enabled: true
  image:
    repository: gsad
    tag: stable
  env:
    GSAD_ARGS: "--listen=0.0.0.0 --http-only --api-only -f"
  volumes:
    - name: gvmdSocket
      mountPath: /run/gvmd

# GVM Config
gvmConfig:
  enabled: true
  image:
    repository: gvm-config
    tag: latest
  env:
    ENABLE_NGINX_CONFIG: true
    ENABLE_TLS_GENERATION: true
  volumes:
    - name: nginx-config
      mountPath: /mnt/nginx/configs
    - name: nginx-certificates
      mountPath: /mnt/nginx/certs

# Nginx
nginx:
  enabled: true
  image:
    repository: nginx
    tag: latest
  ports:
    - name: https
      containerPort: 443
      hostPort: 443
    - name: gvm
      containerPort: 9392
      hostPort: 9392
  volumes:
    - name: nginxConfig
      mountPath: /etc/nginx/conf.d:ro
    - name: nginxCertificates
      mountPath: /etc/nginx/certs:ro
    - name: gsaData
      mountPath: /usr/share/nginx/html:ro

# Configure OpenVAS
configureOpenvas:
  enabled: true
  image:
    repository: openvas-scanner
    tag: stable
  volumes:
    - name: openvasData
      mountPath: /mnt
    - name: openvasLogData
      mountPath: /var/log/openvas
  command:
    - /bin/sh
    - -c
    - |
      printf "table_driven_lsc = yes\nopenvasd_server = http://openvasd:80\n" > /mnt/openvas.conf
      sed "s/127/128/" /etc/openvas/openvas_log.conf | sed 's/gvm/openvas/' > /mnt/openvas_log.conf
      chmod 644 /mnt/openvas.conf
      chmod 644 /mnt/openvas_log.conf
      touch /var/log/openvas/openvas.log
      chmod 666 /var/log/openvas/openvas.log

# OpenVAS
openvas:
  enabled: true
  image:
    repository: openvas-scanner
    tag: stable
  volumes:
    - name: openvasData
      mountPath: /etc/openvas
    - name: openvasLogData
      mountPath: /var/log/openvas
  command:
    - /bin/sh
    - -c
    - |
      cat /etc/openvas/openvas.conf
      tail -f /var/log/openvas/openvas.log

# OpenVASd
openvasd:
  enabled: true
  image:
    repository: openvas-scanner
    tag: stable
  env:
    OPENVASD_MODE: service_notus
    GNUPGHOME: /etc/openvas/gnupg
    LISTENING: 0.0.0.0:80
  volumes:
    - name: openvasData
      mountPath: /etc/openvas
    - name: openvasLogData
      mountPath: /var/log/openvas
    - name: gpgData
      mountPath: /etc/openvas/gnupg
    - name: notusData
      mountPath: /var/lib/notus

# OSPD OpenVAS
ospdOpenvas:
  enabled: true
  image:
    repository: ospd-openvas
    tag: stable
  command:
    [
      "ospd-openvas",
      "-f",
      "--config",
      "/etc/gvm/ospd-openvas.conf",
      "--notus-feed-dir",
      "/var/lib/notus/advisories",
      "-m",
      "666",
    ]
  volumes:
    - name: gpgData
      mountPath: /etc/openvas/gnupg
    - name: vtData
      mountPath: /var/lib/openvas/plugins
    - name: notusData
      mountPath: /var/lib/notus
    - name: ospdOpenvasSocket
      mountPath: /run/ospd
    - name: redisSocket
      mountPath: /run/redis/
    - name: openvasData
      mountPath: /etc/openvas/
    - name: openvasLogData
      mountPath: /var/log/openvas

# Volumes
volumes:
  gpgDataVol:
    enabled: true
    size: 1Gi
  scapDataVol:
    enabled: true
    size: 1Gi
  certDataVol:
    enabled: true
    size: 1Gi
  dataObjectsVol:
    enabled: true
    size: 1Gi
  gvmdDataVol:
    enabled: true
    size: 10Gi
  psqlDataVol:
    enabled: true
    size: 10Gi
  vtDataVol:
    enabled: true
    size: 10Gi
  notusDataVol:
    enabled: true
    size: 1Gi
  psqlSocketVol:
    enabled: true
    size: 1Gi
  gvmdSocketVol:
    enabled: true
    size: 1Gi
  ospdOpenvasSocketVol:
    enabled: true
    size: 1Gi
  redisSocketVol:
    enabled: true
    size: 1Gi
  openvasDataVol:
    enabled: true
    size: 1Gi
  openvasLogDataVol:
    enabled: true
    size: 1Gi
  gsaDataVol:
    enabled: true
    size: 1Gi
  nginxConfigVol:
    enabled: true
    size: 1Gi
  nginxCertificatesVol:
    enabled: true
    size: 1Gi

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# RBAC
rbac:
  create: true
  clusterScoped: true

# Resources
resources: {}

# Node Selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}