{{- if .Values.configureOpenvas.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "greenbone.fullname" . }}-configure-openvas
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "greenbone.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: configure-openvas
          image: {{ include "greenbone.image" (dict "repository" .Values.configureOpenvas.image.repository "tag" .Values.configureOpenvas.image.tag "Chart" .Chart "Values" .Values) }}
          command: {{ .Values.configureOpenvas.command }}
          volumeMounts:
            {{- range .Values.configureOpenvas.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.configureOpenvas.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "greenbone.fullname" $ }}-{{ .name }}vol
        {{- end }}
{{- end }}
