{{- if .Values.gvmConfig.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "greenbone.fullname" . }}-gvm-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "greenbone.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: gvm-config
          image: {{ include "greenbone.image" (dict "repository" .Values.gvmConfig.image.repository "tag" .Values.gvmConfig.image.tag "Chart" .Chart "Values" .Values) }}
          env:
            {{- range $key, $value := .Values.gvmConfig.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- range .Values.gvmConfig.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.gvmConfig.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "greenbone.fullname" $ }}-{{ .name }}Vol
        {{- end }}
{{- end }}