{{- if .Values.gvmd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greenbone.fullname" . }}-gvmd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "greenbone.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gvmd
  template:
    metadata:
      labels:
        {{- include "greenbone.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gvmd
    spec:
      serviceAccountName: {{ include "greenbone.serviceAccountName" . }}
      initContainers:
        - name: wait-for-postgresql
          image: busybox:1.36
          command: ['sh', '-c', 'echo "Waiting for PostgreSQL socket..."; until [ -e /var/run/postgresql/.s.PGSQL.5432 ]; do echo "Waiting..."; sleep 5; done; echo "PostgreSQL ready."']
          volumeMounts:
            - name: psql-socket
              mountPath: /var/run/postgresql
        - name: wait-for-data-objects
          image: bitnami/kubectl:latest
          command: ["sh", "-c", "until kubectl wait --for=condition=complete job -l app.kubernetes.io/component=data-objects --timeout=60s; do echo 'Waiting for job...'; sleep 5; done"]
        - name: wait-for-scap-data
          image: bitnami/kubectl:latest
          command: ["sh", "-c", "until kubectl wait --for=condition=complete job -l app.kubernetes.io/component=scap-data --timeout=60s; do echo 'Waiting for job...'; sleep 5; done"]
        - name: wait-for-cert-bund-data
          image: bitnami/kubectl:latest
          command: ["sh", "-c", "until kubectl wait --for=condition=complete job -l app.kubernetes.io/component=cert-bund-data --timeout=60s; do echo 'Waiting for job...'; sleep 5; done"]
        - name: wait-for-dfn-cert-data
          image: bitnami/kubectl:latest
          command: ["sh", "-c", "until kubectl wait --for=condition=complete job -l app.kubernetes.io/component=dfn-cert-data --timeout=60s; do echo 'Waiting for job...'; sleep 5; done"]
        - name: wait-for-report-formats
          image: bitnami/kubectl:latest
          command: ["sh", "-c", "until kubectl wait --for=condition=complete job -l app.kubernetes.io/component=report-formats --timeout=60s; do echo 'Waiting for job...'; sleep 5; done"]
      containers:
        - name: gvmd
          image: {{ include "greenbone.image" (dict "repository" .Values.gvmd.image.repository "tag" .Values.gvmd.image.tag "Chart" .Chart "Values" .Values) }}
          volumeMounts:
            {{- range .Values.gvmd.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.gvmd.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "greenbone.fullname" $ }}-{{ .name }}vol
        {{- end }}
{{- end }}
