{{- if .Values.notusData.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greenbone.fullname" . }}-notus-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "greenbone.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: notus-data
  template:
    metadata:
      labels:
        {{- include "greenbone.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: notus-data
    spec:
      serviceAccountName: {{ include "greenbone.serviceAccountName" . }}
      containers:
        - name: notus-data
          image: {{ include "greenbone.image" (dict "repository" .Values.notusData.image.repository "tag" .Values.notusData.image.tag "Chart" .Chart "Values" .Values) }}
          env:
            {{- range $key, $value := .Values.notusData.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- range .Values.notusData.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.notusData.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "greenbone.fullname" $ }}-{{ .name }}Vol
        {{- end }}
{{- end }}