{{- range $name, $config := .Values.volumes }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "greenbone.fullname" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "greenbone.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $.Values.global.storageClass }}
  resources:
    requests:
      storage: {{ $config.size }}
{{- end }}
{{- end }}